//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.PartHistoryNewService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPartHistoryOutput", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    public partial class GetPartHistoryOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tests.PartHistoryNewService.ErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnedDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tests.PartHistoryNewService.ErrorCode StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tests.PartHistoryNewService.ErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReady {
            get {
                return this.IsReadyField;
            }
            set {
                if ((this.IsReadyField.Equals(value) != true)) {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnedDocument {
            get {
                return this.ReturnedDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnedDocumentField, value) != true)) {
                    this.ReturnedDocumentField = value;
                    this.RaisePropertyChanged("ReturnedDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tests.PartHistoryNewService.ErrorCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemError = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartHistoryNewService.IPartHistoryNew")]
    public interface IPartHistoryNew {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartHistoryNew/StartPartHistory", ReplyAction="http://tempuri.org/IPartHistoryNew/StartPartHistoryResponse")]
        System.Guid StartPartHistory(int seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartHistoryNew/GetPartHistoryStatus", ReplyAction="http://tempuri.org/IPartHistoryNew/GetPartHistoryStatusResponse")]
        Tests.PartHistoryNewService.GetPartHistoryOutput GetPartHistoryStatus(System.Guid jobId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartHistoryNewChannel : Tests.PartHistoryNewService.IPartHistoryNew, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartHistoryNewClient : System.ServiceModel.ClientBase<Tests.PartHistoryNewService.IPartHistoryNew>, Tests.PartHistoryNewService.IPartHistoryNew {
        
        public PartHistoryNewClient() {
        }
        
        public PartHistoryNewClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartHistoryNewClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartHistoryNewClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartHistoryNewClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid StartPartHistory(int seconds) {
            return base.Channel.StartPartHistory(seconds);
        }
        
        public Tests.PartHistoryNewService.GetPartHistoryOutput GetPartHistoryStatus(System.Guid jobId) {
            return base.Channel.GetPartHistoryStatus(jobId);
        }
    }
}
